/**
 * This exception is thrown to indicate that the operation failed, but an
 * appropriate error message was already printed to the console.  The catch
 * block should not print any error.
 */
export declare class AlreadyReportedError extends Error {
    constructor();
}
//# sourceMappingURL=AlreadyReportedError.d.ts.map